export const words = [
  { french: 'maison', english: 'house', pronunciation: 'meh-zon', sentence: "J'habite dans une maison.", sentenceMeaning: 'I live in a house.' },
  { french: 'livre', english: 'book', pronunciation: 'leev-ruh', sentence: 'Je lis un livre.', sentenceMeaning: 'I am reading a book.' },
  { french: 'ecole', english: 'school', pronunciation: 'ay-kol', sentence: "L'ecole est pres de la maison.", sentenceMeaning: 'The school is near the house.' },
  { french: 'autobus', english: 'bus', pronunciation: 'oh-toh-boos', sentence: "Je prends l'autobus.", sentenceMeaning: 'I take the bus.' },
  { french: 'fenetre', english: 'window', pronunciation: 'fuh-net-ruh', sentence: 'La fenetre est ouverte.', sentenceMeaning: 'The window is open.' },
  { french: 'chaise', english: 'chair', pronunciation: 'shehz', sentence: 'La chaise est confortable.', sentenceMeaning: 'The chair is comfortable.' },
  { french: 'porte', english: 'door', pronunciation: 'port', sentence: 'La porte est fermee.', sentenceMeaning: 'The door is closed.' },
  { french: 'avion', english: 'airplane', pronunciation: 'ah-vyohn', sentence: "L'avion arrive demain.", sentenceMeaning: 'The airplane arrives tomorrow.' },
  { french: 'bonjour', english: 'hello', pronunciation: 'bohn-zhoor', sentence: 'Bonjour, comment ca va?', sentenceMeaning: 'Hello, how are you?' },
  { french: 'merci', english: 'thank you', pronunciation: 'mehr-see', sentence: 'Merci pour le cafe.', sentenceMeaning: 'Thank you for the coffee.' },
  { french: 'famille', english: 'family', pronunciation: 'fah-mee', sentence: "J'aime ma famille.", sentenceMeaning: 'I love my family.' },
  { french: 'ami', english: 'friend', pronunciation: 'ah-mee', sentence: 'Mon ami arrive bientot.', sentenceMeaning: 'My friend arrives soon.' },
  { french: 'eau', english: 'water', pronunciation: 'oh', sentence: "Je bois de l'eau.", sentenceMeaning: 'I drink water.' },
  { french: 'the', english: 'tea', pronunciation: 'tay', sentence: 'Le the est chaud.', sentenceMeaning: 'The tea is hot.' },
  { french: 'cafe', english: 'coffee', pronunciation: 'kah-fay', sentence: 'Je prends un cafe.', sentenceMeaning: 'I am having a coffee.' },
  { french: 'pain', english: 'bread', pronunciation: 'pan', sentence: 'Le pain est frais.', sentenceMeaning: 'The bread is fresh.' },
  { french: 'riz', english: 'rice', pronunciation: 'ree', sentence: 'Je prepare du riz.', sentenceMeaning: 'I am preparing rice.' },
  { french: 'pomme', english: 'apple', pronunciation: 'pum', sentence: 'La pomme est rouge.', sentenceMeaning: 'The apple is red.' },
  { french: 'banane', english: 'banana', pronunciation: 'bah-nan', sentence: 'Je mange une banane.', sentenceMeaning: 'I eat a banana.' },
  { french: 'lait', english: 'milk', pronunciation: 'lay', sentence: 'Le lait est froid.', sentenceMeaning: 'The milk is cold.' },
  { french: 'soupe', english: 'soup', pronunciation: 'soop', sentence: 'La soupe est bonne.', sentenceMeaning: 'The soup is good.' },
  { french: 'salade', english: 'salad', pronunciation: 'sah-lad', sentence: 'Je fais une salade.', sentenceMeaning: 'I make a salad.' },
  { french: 'table', english: 'table', pronunciation: 'tahbl', sentence: 'La table est propre.', sentenceMeaning: 'The table is clean.' },
  { french: 'lit', english: 'bed', pronunciation: 'lee', sentence: 'Le lit est confortable.', sentenceMeaning: 'The bed is comfortable.' },
  { french: 'lampe', english: 'lamp', pronunciation: 'lahmp', sentence: 'La lampe est allumee.', sentenceMeaning: 'The lamp is on.' },
  { french: 'jardin', english: 'garden', pronunciation: 'zhar-dan', sentence: 'Le jardin est beau.', sentenceMeaning: 'The garden is beautiful.' },
  { french: 'fleur', english: 'flower', pronunciation: 'fluhr', sentence: 'La fleur est rose.', sentenceMeaning: 'The flower is pink.' },
  { french: 'arbre', english: 'tree', pronunciation: 'arbr', sentence: "L'arbre est grand.", sentenceMeaning: 'The tree is tall.' },
  { french: 'soleil', english: 'sun', pronunciation: 'soh-lay', sentence: 'Le soleil brille.', sentenceMeaning: 'The sun is shining.' },
  { french: 'pluie', english: 'rain', pronunciation: 'plwee', sentence: 'La pluie tombe doucement.', sentenceMeaning: 'The rain falls softly.' },
  { french: 'neige', english: 'snow', pronunciation: 'nehzh', sentence: 'La neige est blanche.', sentenceMeaning: 'The snow is white.' },
  { french: 'ville', english: 'city', pronunciation: 'veel', sentence: 'La ville est grande.', sentenceMeaning: 'The city is big.' },
  { french: 'rue', english: 'street', pronunciation: 'roo', sentence: 'La rue est calme.', sentenceMeaning: 'The street is quiet.' },
  { french: 'voiture', english: 'car', pronunciation: 'vwah-toor', sentence: 'La voiture est bleue.', sentenceMeaning: 'The car is blue.' },
  { french: 'train', english: 'train', pronunciation: 'tran', sentence: 'Le train part a huit heures.', sentenceMeaning: 'The train leaves at eight.' },
  { french: 'velo', english: 'bike', pronunciation: 'vay-loh', sentence: 'Je roule a velo.', sentenceMeaning: 'I ride a bike.' },
  { french: 'magasin', english: 'store', pronunciation: 'mah-gah-zan', sentence: 'Le magasin est ouvert.', sentenceMeaning: 'The store is open.' },
  { french: 'marche', english: 'market', pronunciation: 'mar-shay', sentence: 'Je vais au marche.', sentenceMeaning: 'I am going to the market.' },
  { french: 'argent', english: 'money', pronunciation: 'ar-zhahn', sentence: "J'ai de l'argent.", sentenceMeaning: 'I have money.' },
  { french: 'sac', english: 'bag', pronunciation: 'sak', sentence: 'Mon sac est leger.', sentenceMeaning: 'My bag is light.' },
  { french: 'cle', english: 'key', pronunciation: 'klay', sentence: 'La cle est sur la table.', sentenceMeaning: 'The key is on the table.' },
  { french: 'telephone', english: 'phone', pronunciation: 'tay-lay-fon', sentence: 'Mon telephone sonne.', sentenceMeaning: 'My phone is ringing.' },
  { french: 'ordinateur', english: 'computer', pronunciation: 'or-dee-nah-tuhr', sentence: "L'ordinateur est rapide.", sentenceMeaning: 'The computer is fast.' },
  { french: 'photo', english: 'photo', pronunciation: 'foh-toh', sentence: 'La photo est jolie.', sentenceMeaning: 'The photo is pretty.' },
  { french: 'musique', english: 'music', pronunciation: 'moo-zeek', sentence: "J'ecoute de la musique.", sentenceMeaning: 'I listen to music.' },
  { french: 'film', english: 'movie', pronunciation: 'feelm', sentence: 'Le film commence.', sentenceMeaning: 'The movie begins.' },
  { french: 'cuisine', english: 'kitchen', pronunciation: 'kwee-zeen', sentence: 'La cuisine est propre.', sentenceMeaning: 'The kitchen is clean.' },
  { french: 'chambre', english: 'bedroom', pronunciation: 'shahm-bruh', sentence: 'Ma chambre est calme.', sentenceMeaning: 'My bedroom is calm.' },
  { french: 'salle', english: 'room', pronunciation: 'sal', sentence: 'La salle est grande.', sentenceMeaning: 'The room is large.' },
  { french: 'matin', english: 'morning', pronunciation: 'mah-tan', sentence: 'Le matin est paisible.', sentenceMeaning: 'The morning is peaceful.' },
  { french: 'soir', english: 'evening', pronunciation: 'swahr', sentence: 'Le soir est frais.', sentenceMeaning: 'The evening is cool.' },
  { french: 'jour', english: 'day', pronunciation: 'zhoor', sentence: 'C est un beau jour.', sentenceMeaning: 'It is a beautiful day.' },
  { french: 'semaine', english: 'week', pronunciation: 'suh-men', sentence: 'La semaine commence.', sentenceMeaning: 'The week begins.' },
  { french: 'mois', english: 'month', pronunciation: 'mwah', sentence: 'Le mois de mai est doux.', sentenceMeaning: 'The month of May is gentle.' },
  { french: 'heure', english: 'hour/time', pronunciation: 'uhr', sentence: 'Quelle heure est-il?', sentenceMeaning: 'What time is it?' },
  { french: 'minute', english: 'minute', pronunciation: 'mee-noot', sentence: 'Une minute, s il vous plait.', sentenceMeaning: 'One minute, please.' },
  { french: 'aujourd hui', english: 'today', pronunciation: 'oh-zhoor-dwee', sentence: "Aujourd hui, je marche.", sentenceMeaning: 'Today, I walk.' },
  { french: 'demain', english: 'tomorrow', pronunciation: 'duh-man', sentence: 'Demain, je cuisine.', sentenceMeaning: 'Tomorrow, I cook.' },
  { french: 'hier', english: 'yesterday', pronunciation: 'yehr', sentence: 'Hier, j ai lu.', sentenceMeaning: 'Yesterday, I read.' },
  { french: 'petit', english: 'small', pronunciation: 'puh-tee', sentence: 'Le sac est petit.', sentenceMeaning: 'The bag is small.' },
  { french: 'grand', english: 'big/tall', pronunciation: 'grahn', sentence: 'Le jardin est grand.', sentenceMeaning: 'The garden is big.' },
  { french: 'bon', english: 'good', pronunciation: 'bohn', sentence: 'Le repas est bon.', sentenceMeaning: 'The meal is good.' },
  { french: 'beau', english: 'beautiful', pronunciation: 'boh', sentence: 'Le ciel est beau.', sentenceMeaning: 'The sky is beautiful.' },
  { french: 'chaud', english: 'hot', pronunciation: 'shoh', sentence: 'Le cafe est chaud.', sentenceMeaning: 'The coffee is hot.' },
  { french: 'froid', english: 'cold', pronunciation: 'fwah', sentence: "L eau est froide.", sentenceMeaning: 'The water is cold.' },
  { french: 'heureux', english: 'happy', pronunciation: 'uh-ruh', sentence: 'Je suis heureux.', sentenceMeaning: 'I am happy.' },
  { french: 'calme', english: 'calm', pronunciation: 'kalm', sentence: 'La maison est calme.', sentenceMeaning: 'The house is calm.' },
  { french: 'facile', english: 'easy', pronunciation: 'fah-seel', sentence: 'La phrase est facile.', sentenceMeaning: 'The sentence is easy.' },
  { french: 'difficile', english: 'difficult', pronunciation: 'dee-fee-seel', sentence: 'Le mot est difficile.', sentenceMeaning: 'The word is difficult.' },
  { french: 'nouveau', english: 'new', pronunciation: 'noo-voh', sentence: 'C est un nouveau livre.', sentenceMeaning: 'It is a new book.' },
  { french: 'ancien', english: 'old/former', pronunciation: 'ahn-see-an', sentence: 'C est un ancien batiment.', sentenceMeaning: 'It is an old building.' },
  { french: 'manger', english: 'to eat', pronunciation: 'mahn-zhay', sentence: 'Je veux manger.', sentenceMeaning: 'I want to eat.' },
  { french: 'boire', english: 'to drink', pronunciation: 'bwahr', sentence: 'Je vais boire de l eau.', sentenceMeaning: 'I am going to drink water.' },
  { french: 'aller', english: 'to go', pronunciation: 'ah-lay', sentence: 'Je vais au jardin.', sentenceMeaning: 'I go to the garden.' },
  { french: 'venir', english: 'to come', pronunciation: 'vuh-neer', sentence: 'Elle va venir demain.', sentenceMeaning: 'She will come tomorrow.' },
  { french: 'faire', english: 'to do/make', pronunciation: 'fehr', sentence: 'Je fais une salade.', sentenceMeaning: 'I make a salad.' },
  { french: 'lire', english: 'to read', pronunciation: 'leer', sentence: 'Je lis le journal.', sentenceMeaning: 'I read the newspaper.' },
  { french: 'ecrire', english: 'to write', pronunciation: 'ay-kreer', sentence: "J ecris une note.", sentenceMeaning: 'I write a note.' },
  { french: 'parler', english: 'to speak', pronunciation: 'par-lay', sentence: 'Je parle francais.', sentenceMeaning: 'I speak French.' },
  { french: 'ecouter', english: 'to listen', pronunciation: 'ay-koo-tay', sentence: "J ecoute la radio.", sentenceMeaning: 'I listen to the radio.' },
  { french: 'regarder', english: 'to watch/look at', pronunciation: 'ruh-gar-day', sentence: 'Je regarde une photo.', sentenceMeaning: 'I look at a photo.' },
  { french: 'aimer', english: 'to like/love', pronunciation: 'eh-may', sentence: "J aime le jardin.", sentenceMeaning: 'I like the garden.' },
  { french: 'trouver', english: 'to find', pronunciation: 'troo-vay', sentence: 'Je trouve la cle.', sentenceMeaning: 'I find the key.' },
  { french: 'donner', english: 'to give', pronunciation: 'doh-nay', sentence: 'Je donne un livre.', sentenceMeaning: 'I give a book.' },
  { french: 'prendre', english: 'to take', pronunciation: 'prahn-druh', sentence: 'Je prends le train.', sentenceMeaning: 'I take the train.' },
  { french: 'ouvrir', english: 'to open', pronunciation: 'oo-vreer', sentence: "J ouvre la porte.", sentenceMeaning: 'I open the door.' },
  { french: 'fermer', english: 'to close', pronunciation: 'fehr-may', sentence: 'Je ferme la fenetre.', sentenceMeaning: 'I close the window.' },
  { french: 'dormir', english: 'to sleep', pronunciation: 'dor-meer', sentence: 'Je dors bien.', sentenceMeaning: 'I sleep well.' },
  { french: 'marcher', english: 'to walk', pronunciation: 'mar-shay', sentence: 'Je marche le matin.', sentenceMeaning: 'I walk in the morning.' },
  { french: 'acheter', english: 'to buy', pronunciation: 'ahsh-tay', sentence: "J achete du pain.", sentenceMeaning: 'I buy bread.' },
  { french: 'porter', english: 'to wear/carry', pronunciation: 'por-tay', sentence: 'Je porte un sac.', sentenceMeaning: 'I carry a bag.' },
  { french: 'mere', english: 'mother', pronunciation: 'mehr', sentence: 'Ma mere sourit.', sentenceMeaning: 'My mother smiles.' },
  { french: 'pere', english: 'father', pronunciation: 'pehr', sentence: 'Mon pere cuisine.', sentenceMeaning: 'My father cooks.' },
  { french: 'fils', english: 'son', pronunciation: 'fees', sentence: 'Son fils etudie.', sentenceMeaning: 'Her son studies.' },
  { french: 'fille', english: 'daughter/girl', pronunciation: 'fee', sentence: 'Sa fille chante.', sentenceMeaning: 'Her daughter sings.' },
  { french: 'frere', english: 'brother', pronunciation: 'frehr', sentence: 'Mon frere arrive.', sentenceMeaning: 'My brother arrives.' },
  { french: 'soeur', english: 'sister', pronunciation: 'suhr', sentence: 'Ma soeur lit.', sentenceMeaning: 'My sister reads.' },
  { french: 'medecin', english: 'doctor', pronunciation: 'med-san', sentence: 'Le medecin est gentil.', sentenceMeaning: 'The doctor is kind.' },
  { french: 'dentiste', english: 'dentist', pronunciation: 'dahn-teest', sentence: 'Le dentiste travaille.', sentenceMeaning: 'The dentist works.' },
  { french: 'rendez vous', english: 'appointment', pronunciation: 'rahn-day-voo', sentence: "J ai un rendez vous.", sentenceMeaning: 'I have an appointment.' },
  { french: 'sante', english: 'health', pronunciation: 'sahn-tay', sentence: 'La sante est importante.', sentenceMeaning: 'Health is important.' },
  { french: 'repos', english: 'rest', pronunciation: 'ruh-poh', sentence: 'Le repos aide le corps.', sentenceMeaning: 'Rest helps the body.' },
  { french: 'coeur', english: 'heart', pronunciation: 'kuhr', sentence: 'Le coeur est fort.', sentenceMeaning: 'The heart is strong.' },
  { french: 'main', english: 'hand', pronunciation: 'man', sentence: 'Ma main est froide.', sentenceMeaning: 'My hand is cold.' },
  { french: 'yeux', english: 'eyes', pronunciation: 'yuh', sentence: 'Ses yeux sont bruns.', sentenceMeaning: 'Her eyes are brown.' },
  { french: 'cheveux', english: 'hair', pronunciation: 'shuh-vuh', sentence: 'Ses cheveux sont longs.', sentenceMeaning: 'Her hair is long.' },
  { french: 'sourire', english: 'smile', pronunciation: 'soo-reer', sentence: 'Son sourire est doux.', sentenceMeaning: 'Her smile is gentle.' },
  { french: 'calendrier', english: 'calendar', pronunciation: 'kah-lahn-dree-ay', sentence: 'Le calendrier est utile.', sentenceMeaning: 'The calendar is useful.' },
  { french: 'recette', english: 'recipe', pronunciation: 'ruh-set', sentence: 'La recette est simple.', sentenceMeaning: 'The recipe is simple.' },
  { french: 'memoire', english: 'memory', pronunciation: 'may-mwahr', sentence: 'Cette memoire est belle.', sentenceMeaning: 'This memory is beautiful.' }
];

export const verbs = [
  {
    infinitive: 'manger',
    meaning: 'to eat',
    pronunciation: 'mahn-zhay',
    present: ['je mange', 'tu manges', 'il/elle mange', 'nous mangeons', 'vous mangez', 'ils/elles mangent'],
    passe: ["j'ai mange", 'tu as mange', 'il/elle a mange', 'nous avons mange', 'vous avez mange', 'ils/elles ont mange'],
    future: ['je mangerai', 'tu mangeras', 'il/elle mangera', 'nous mangerons', 'vous mangerez', 'ils/elles mangeront']
  },
  {
    infinitive: 'marcher',
    meaning: 'to walk',
    pronunciation: 'mar-shay',
    present: ['je marche', 'tu marches', 'il/elle marche', 'nous marchons', 'vous marchez', 'ils/elles marchent'],
    passe: ["j'ai marche", 'tu as marche', 'il/elle a marche', 'nous avons marche', 'vous avez marche', 'ils/elles ont marche'],
    future: ['je marcherai', 'tu marcheras', 'il/elle marchera', 'nous marcherons', 'vous marcherez', 'ils/elles marcheront']
  },
  {
    infinitive: 'parler',
    meaning: 'to speak',
    pronunciation: 'par-lay',
    present: ['je parle', 'tu parles', 'il/elle parle', 'nous parlons', 'vous parlez', 'ils/elles parlent'],
    passe: ["j'ai parle", 'tu as parle', 'il/elle a parle', 'nous avons parle', 'vous avez parle', 'ils/elles ont parle'],
    future: ['je parlerai', 'tu parleras', 'il/elle parlera', 'nous parlerons', 'vous parlerez', 'ils/elles parleront']
  }
];

export const pronouns = [
  ['je', 'I'],
  ['tu', 'you, informal'],
  ['il / elle', 'he / she'],
  ['nous', 'we'],
  ['vous', 'you, formal or plural'],
  ['ils / elles', 'they']
];
