const wellnessQuotes = [
  'Small **steps** every day become the path to lasting **strength**.',
  'Your body hears everything your heart believes. Speak **gently**.',
  '**Wellness** is not a finish line. It is a kind conversation with yourself.',
  '**Movement** is a celebration of what you can do today.',
  'Rest is productive when it returns you to **yourself**.',
  '**Progress** blooms quietly, then all at once.',
  'Choose the habit that **loves** you back.',
  'You do not need a perfect day to make a **beautiful** choice.',
  'Health grows in the routines that feel **kind** enough to keep.',
  'A calm morning can become a **steady** day.',
  'One kind choice is still a **powerful** choice.',
  'The smallest ritual can become a source of **strength**.',
  'Breathe in **patience**, breathe out pressure.',
  'Let today be **gentle** and still count.',
  'A little **consistency** can carry a lot of love.',
  'Your pace is allowed to be **peaceful**.',
  '**Care** for yourself as someone deeply worth caring for.',
  'The good you notice gets **easier** to find.',
  'Energy returns when rest is treated with **respect**.',
  'A **grateful** heart makes ordinary moments shine.',
  'Strong days and soft days both **belong**.',
  'A healthy life is built from **loving** details.',
  'Today is a fresh chance to be on your own **side**.',
  '**Joy** can be simple and still be enough.',
  'Listen to your body with **kindness** first.',
  'Every nourishing choice is a quiet **celebration**.',
  'You are allowed to begin **again** as many times as you need.',
  '**Peace** is part of wellness too.',
  'Your future self is grateful for small **care** today.',
  'Notice the **good**, even if it was quiet.',
  'A nourishing meal is a little note of **care** to your future self.',
  'Your **worth** is not measured in what you accomplish today.',
  'Be as **patient** with yourself as you are with the people you love most.',
  'The body keeps **score**. Let it feel safe today.',
  '**Rest** is not a reward. It is a requirement.',
  'Some days just showing up is the **bravest** thing you can do.',
  'You are allowed to take up **space** and move slowly.',
  'Nourishment is an act of **self-respect**, not indulgence.',
  'Your breath is always available as an anchor. **Breathe**.',
  'Healing is not linear. **Gentle** is still progress.',
  '**Consistency** matters more than perfection ever will.',
  'The version of you who rested is just as **worthy**.',
  'Growth happens in the pauses, not only the push. **Pause**.',
  'Do one kind thing for your body today. That is **enough**.',
  'You deserve the same **compassion** you give so freely to others.',
  'A body that is listened to feels **safe** enough to heal.',
  '**Hydrate**, rest, breathe, repeat. The simplest loops are the most powerful.',
  'Your best will look different every day. That is **normal**.',
  'Tired is not lazy. Rest is not **giving up**.',
  'Small acts of **care** compounded over time become transformation.',
  'You do not have to earn your **rest**.',
  'Trust the slow work. Every gentle step **counts**.',
  'The most loving thing you can do today might be to simply **stop**.',
  '**Gratitude** turns what you have into enough.',
  'A moment of stillness is a gift you give your nervous **system**.',
  'Progress is invisible until it is suddenly **undeniable**.',
  'Let today be about **effort**, not outcome.',
  'You are not behind. You are exactly where your **journey** needs you.',
  'Taking care of yourself is a radical act of **love**.',
  'Every deep breath is a small vote for your own **wellbeing**.',
  'Your routine is your **sanctuary**. Protect it gently.',
  'Some seasons call for **softness**, not strength.',
  'The habit of **noticing** is the start of changing.',
  'Wellness begins with one honest, **kind** thought about yourself.',
  'You have already done hard things. **Today** is another one you will get through.',
  'What you call rest, your cells call **repair**.',
  'Choose **nourishment** over punishment, always.',
  'A joyful body is a well-**tended** one.',
  'You are not failing. You are **learning** at a pace that is right for you.'
];

export function getDailyQuote(date = new Date()) {
  const dayStart = Date.UTC(date.getFullYear(), date.getMonth(), date.getDate());
  const yearStart = Date.UTC(date.getFullYear(), 0, 1);
  const dayOfYear = Math.floor((dayStart - yearStart) / 86_400_000);
  return wellnessQuotes[dayOfYear % wellnessQuotes.length];
}

